/**
 * TelegramTabBarViewManager.m
 *
 * Objective-C bridge file for TelegramTabBarViewManager.
 *
 * RCT_EXTERN_MODULE declares the Swift class to the React Native runtime.
 * Each RCT_EXPORT_VIEW_PROPERTY maps a JS prop name + ObjC type to the
 * corresponding Swift setter generated by the ViewManager.
 *
 * Keep prop names and types in sync with:
 *   - TelegramTabBarViewManager.swift  (setter implementations)
 *   - src/types/nativeProps.ts         (TypeScript prop interface)
 */

#import <React/RCTViewManager.h>
#import <React/RCTBridgeModule.h>

// RCT_EXTERN_MODULE uses __attribute__((constructor)) which can be dead-stripped
// by the Apple linker when building with use_frameworks! :linkage => :static.
// Adding +load to a class in this translation unit prevents the linker from
// removing the entire object file, ensuring the constructor runs at startup.
@interface TelegramTabBarModuleLoader : NSObject
@end
@implementation TelegramTabBarModuleLoader
+ (void)load {}
@end

@interface RCT_EXTERN_MODULE(TelegramTabBarViewManager, RCTViewManager)

// ── Tab data ─────────────────────────────────────────────────────────────────
/// Array of tab descriptor objects: { key, title, svgPaths? }
RCT_EXPORT_VIEW_PROPERTY(tabs, NSArray)

// ── Active state ─────────────────────────────────────────────────────────────
/// Zero-based index of the currently selected tab.
RCT_EXPORT_VIEW_PROPERTY(activeIndex, NSInteger)

// ── Theme ─────────────────────────────────────────────────────────────────────
/// Colour theme object: { backgroundColor, activeColor, inactiveColor, indicatorColor }
RCT_EXPORT_VIEW_PROPERTY(theme, NSDictionary)

// ── Layout ────────────────────────────────────────────────────────────────────
/// Safe-area bottom inset in points (from useSafeAreaInsets().bottom on the JS side).
RCT_EXPORT_VIEW_PROPERTY(bottomInset, CGFloat)

// ── Visibility ────────────────────────────────────────────────────────────────
/// Controls tab bar visibility with a slide-in/out animation (hide-on-scroll).
RCT_EXPORT_VIEW_PROPERTY(isVisible, BOOL)

// ── Badges ────────────────────────────────────────────────────────────────────
/// Array of badge descriptor objects: { key, count?, dot? }
RCT_EXPORT_VIEW_PROPERTY(tabBadges, NSArray)

// ── Events ────────────────────────────────────────────────────────────────────
/// Fired on tap: nativeEvent.key = tapped tab key.
RCT_EXPORT_VIEW_PROPERTY(onTabPress, RCTBubblingEventBlock)

/// Fired on long press: nativeEvent.key = long-pressed tab key.
RCT_EXPORT_VIEW_PROPERTY(onTabLongPress, RCTBubblingEventBlock)

@end
